### ISSUE TITLE
Customize appearance

### ISSUE THREAD

**Issue by namelivia** [fjies/ocDashboard#104]
![2014-11-23-202518_678x534_scrot](https://cloud.githubusercontent.com/assets/1571416/5158891/ca51592e-734e-11e4-8f31-8bdadced3adf.png)

I've been experimenting with customization, basically I'm modifying three parameters:

- Background image
- widget transparency
- widget border radius

In order to make them look more like the Chrome or Firefox start page.
It's working right now but I have some issues in order to make it work as I want and make a commit.

1. Setting the appearance: This is done by jQuery, before the widgets are faded in it takes the appearance settings and apply them.

2. Passing the appearance settings to jQuery: For doing this I'm writing them using php in a hidden field in the template that later will be read by jQuery. I don't know if this way is good or bad, and if there is another best way of doing it.

3. Setting and getting the appearance settings using permanent storage (database?). This is the point that I'm not being able to do, and I will need some clue. How and where can I save those parameters?

Thanks, and congratulations for this great project.

**Comment by fjies** [comment]
look at the new structure, there is one css file that can be edited etc.
