### ISSUE TITLE
https invalid due to http link to weather icons

### ISSUE THREAD

**Issue by zeigerpuppy** [fjies/ocDashboard#56]
When running in owncloud 6.0.3 under SSL, the page does not validate if weather widget is active.
This is due to the link to yahoo images being http://l.yimg.com/a/i/us/we/52/?.gif

I replaced this with local images instead 
private $imageUrl = "https://fqdn.com/owncloud/images/FlatBlack_sm/?.png";
images were shrunk versions of these icons sets (GPL):
https://rcos-user-interface-research.googlecode.com/svn/trunk/MockUps/Flat%20Weather%20Icons%20English/Flat%20Black/

I used a web link rather than a local link due to the icons having a different address when they load at start on login as opposed to when "Desktop" is selected from the menu (? does local context change, this is probably a bug).

I believe local icon sets are better but I guess that's the developer's choice.

Also, would be awesome if the widget offered the option to use http://openweathermap.org/ as an alternative to yahoo, API for PHP is described here: https://github.com/cmfcmf/OpenWeatherMap-PHP-Api

**Comment by fjies** [comment]
please try new version 1.5.6beta.
