### ISSUE TITLE
wrong URL onDashboard header links

### ISSUE THREAD

**Issue by zeigerpuppy** [fjies/ocDashboard#92]
ocDashboard with owncloud 6.0.3 works fine on my server apart from the links at the top of the widgets leading to the wrong URL.
ocDashboard seems to be grabbbing these URLs form the local webserver's hostname but this is a problem as I am running owncloud on nginx (port 8443) behind an apache proxy.
This results in the link URLs being malformed:
https://myserver.fqd:8443/owncloud
instead of https://myserver.fqd/owncloud
Is there a way to manually set the the URL base that ocDashboard uses?

**Comment by fjies** [comment]
please try version 1.5.6beta.
